<?php
  
  session_start();  // iniciando la sesión.....
  session_unset();//elimina todas las variables de sesión.....
  session_destroy(); // eliminar la sesión por completo.....
  header("Location: index.php");
  exit();
